### ISSUE TITLE
Connection works with sstpc, not with iSSTP.

### ISSUE THREAD

**Issue by fenix849** [axot/isstp#10]
Trying to connect with iSSTP on an OSX Catalina Mac.

Main window:
![isstp-main](https://user-images.githubusercontent.com/5925839/78521777-550cd100-780e-11ea-81e1-86567fe99a77.png)

Advanced Options Window:
![isstp-advanced](https://user-images.githubusercontent.com/5925839/78521828-8eddd780-780e-11ea-9f59-8cc7ebb517fa.png)

sstpc working log:

infxadmin$ sudo /usr/local/sbin/sstpc --log-stderr --log-level 3  erwhvpn*removed*> --user infx --password "*removed*" require-mschap-v2 refuse-eap refuse-chap refuse-pap refuse-mschap nobsdcomp nodeflate usepeerdns noauth
Apr  6 13:05:47 sstpc[6794]: Resolved erwhvpn.ixaninite.org.au to 115.70.204.22
Apr  6 13:05:47 sstpc[6794]: Connected to erwhvpn.ixaninite.org.au
Apr  6 13:05:47 sstpc[6794]: Sending Connect-Request Message
Apr  6 13:05:47 sstpc[6794]: Started PPP Link Negotiation
Apr  6 13:05:48 sstpc[6794]: Sending Connected Message
Apr  6 13:05:48 sstpc[6794]: Connection Established
Apr  6 13:08:10 sstpc[6794]: Sending Echo-Request Message
Apr  6 13:09:10 sstpc[6794]: Sending Echo-Request Message

In iSSTP i simply get "Not Connected!" after a few seconds trying.

**Comment by axot** [comment]
Could you try the latest version? Maybe you can also change the password if it contains some symbols should be escaped which iSstp did not handle as well?
