### ISSUE TITLE
SSTP With certificate

### ISSUE THREAD

**Issue by jtsfvieira** [axot/isstp#11]
Hi all,

We have some computers that need access to azure VPN but on windows the method to sign in is only certificate without user and password.

![image](https://user-images.githubusercontent.com/68940538/91555606-3e842500-e929-11ea-9485-37a6fba97613.png)

Its posible with iSSTP?

Thanks.
João

**Comment by axot** [comment]
I checked upstream feature, not support at this time.
https://sourceforge.net/p/sstp-client/discussion/1499217/thread/f5e54616/
