### ISSUE TITLE
update needed for M1 based Macs?

### ISSUE THREAD

**Issue by kai-uwe-rommel** [axot/isstp#12]
I Got this working on an Intel based MacBook Pro. But on a M1 based brand new one it does not connect. How do I debug this e.g. why? Or is this a know problem and someone needs to update this SSTP client for M1?

**Comment by axot** [comment]
Thanks for the feedback, let me check it.

**Comment by axot** [comment]
I made it running on my M1 machine, so a new version will be released soon which using homebrew version's sstp-client. More works for adopting new swift syntax.

**Comment by kai-uwe-rommel** [comment]
Great, thanks, I'm looking forward to this. 
Please include instructions with it on how to install/configure it in conjunction with homebrew.
I'm rather a novice user/admin for MacOS (not using it myself but helping a couple of our users).

**Comment by axot** [comment]
@kai-uwe-rommel Could you give a test on [iSstp.v1.4-rc1.zip](https://github.com/axot/isstp/releases/download/v1.4-rc1/iSstp.v1.4-rc1.zip). No additional steps need for homebrew package concern.

**Comment by kai-uwe-rommel** [comment]
Unfortunately, it does not even start on my Mac.
I downloaded the ZIP file onto the Mac's desktop.
Double clicked it so it was unpacked to the Desktop and I have the iSstp icon.
But any double click on it simply flashes briefly and nothing more happens.

**Comment by axot** [comment]
@kai-uwe-rommel , so is there an icon in the menu bar as the following screen shot?

<img width="595" alt="image" src="https://user-images.githubusercontent.com/611054/130959680-227edc3d-a5db-4c46-97ec-5d333efd7725.png">

Also can you check `Security & Privacy` setting in `System Preferences`?
You have to choose `App store and identified develops` option and make sure isstp didn't blocked there.

![image](https://user-images.githubusercontent.com/611054/130959892-1c8bcaab-c922-4db9-8e5b-9b743784bbf6.png)

**Comment by kai-uwe-rommel** [comment]
I installed sstp-client via homebrew and got this working.
But, of course, it is awkward to use purely by terminal and it would be great to get your GUI going.

**Comment by kai-uwe-rommel** [comment]
I now only saw your comments.
No, there was no icon at top.
Also, I don't think it was blocked by security - probably there was still my exception from the previous version.

However, now after I had installed sstp-client via homebrew, NOW iSstp opens!
(And it not only opens but also works properly.)

Perhaps some missing prerequisite that now got installed via homebrew as a "side effect"?

**Comment by axot** [comment]
This version should work without any homebrew packages.
Did you install rosetta 2 on your M1 mac? And if possible could you execute the following commands, then paste the results, please remove any sensitive information there.

Assume you put iSstp.app in Desktop.
```
$ ~/Desktop/iSstp.app/Contents/MacOS/iSstp
$ otool -L ~/Desktop/iSstp.app/Contents/Resources/sstpc
$ ~/Desktop/iSstp.app/Contents/Resources/sstpc
```

**Comment by axot** [comment]
oops, I may found the reason, the main program is using some homebrew packages.
```
$ otool -L ~/Desktop/iSstp.app/Contents/MacOS/iSstp
/Users/axot/Desktop/iSstp.app/Contents/MacOS/iSstp:
	/opt/homebrew/opt/libevent/lib/libevent-2.1.7.dylib (compatibility version 8.0.0, current version 8.1.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
	/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	/usr/lib/swift/libswiftAppKit.dylib (compatibility version 1.0.0, current version 104.0.0, weak)
	/usr/lib/swift/libswiftCloudKit.dylib (compatibility version 1.0.0, current version 982.0.0, weak)
	/usr/lib/swift/libswiftCore.dylib (compatibility version 1.0.0, current version 1205.0.24)
	/usr/lib/swift/libswiftCoreData.dylib (compatibility version 1.0.0, current version 3.0.0, weak)
	/usr/lib/swift/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 1.6.0, weak)
	/usr/lib/swift/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 2.0.0, weak)
	/usr/lib/swift/libswiftCoreImage.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
	/usr/lib/swift/libswiftCoreLocation.dylib (compatibility version 1.0.0, current version 5.0.0, weak)
	/usr/lib/swift/libswiftDarwin.dylib (compatibility version 1.0.0, current version 0.0.0, weak)
	/usr/lib/swift/libswiftDispatch.dylib (compatibility version 1.0.0, current version 4.100.1)
	/usr/lib/swift/libswiftFoundation.dylib (compatibility version 1.0.0, current version 25.102.0)
	/usr/lib/swift/libswiftIOKit.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
	/usr/lib/swift/libswiftMetal.dylib (compatibility version 1.0.0, current version 1.3.1, weak)
	/usr/lib/swift/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 3.0.0, weak)
	/usr/lib/swift/libswiftQuartzCore.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
	/usr/lib/swift/libswiftXPC.dylib (compatibility version 1.0.0, current version 1.1.0, weak)
```

**Comment by kai-uwe-rommel** [comment]
Yes, I had noticed that rosetta was installed before.

Of course, since it now starts, the commands do not reveal any problem.
On iSstp I also see the same dependencies on libevent and openssl from howbrew.

**Comment by kai-uwe-rommel** [comment]
I don't see a problem with with the dependencies in general.
As long as you document the requirements ... I guess most of the target users for iSstp will have homebrew anyway.
Otherwise you would have to package them with iSstp.
Perhaps it may even be better if openssl is regularly refreshed with homebrew to avoid use of an outdated one.
As long as all works together and iSstp is not broken by a newer openssl.

**Comment by axot** [comment]
Yes, once you install sstp-client via homebrew, the dependencies were also installed.
Just uninstall these packages with

```
brew rm libevent openssl@1.1
```

iSstp.app should stop working.

**Comment by axot** [comment]
Here I build a rc2 version which removed these dependencies.
[iSstp.v1.4-rc2.zip](https://github.com/axot/isstp/files/7059798/iSstp.v1.4-rc2.zip)

**Comment by axot** [comment]
> Perhaps it may even be better if openssl is regularly refreshed with homebrew to avoid use of an outdated one.

Yes, you can do this with `Use external sstpc` feature.
![image](https://user-images.githubusercontent.com/611054/130965393-1812aabe-6a82-48e3-b93d-773c8b0f8cef.png)

**Comment by kai-uwe-rommel** [comment]
Hmm. I got the rc2 version and tried ... no connect.
I directly ran the /Applications/Utilities/iSstp.app/Contents/Resources/sstpc (where I installed it) with the appropriate options and it worked (but had to run it as root due to the "noauth").
I was connected and could ping etc.
The GUI ... does it run sstpc as root? I guess not?
Was this not required before?
What could I have done wrong now?

**Comment by axot** [comment]
Yes, you are right, we run sstpc as root, please use this rc3 version, it should fix the permission issue.
[iSstp.v1.4-rc3.zip](https://github.com/axot/isstp/files/7063319/iSstp.v1.4-rc3.zip)

**Comment by kai-uwe-rommel** [comment]
Thanks for the update. This version now works fine again!
E.g. can become a release. :-)

**Comment by axot** [comment]
Thanks for your help!

**Comment by axot** [comment]
I will close this issue.
