### ISSUE TITLE
[bug] Unable to connect on new version with intel based mac

### ISSUE THREAD

**Issue by ghost** [axot/isstp#13]
Hello,

It seems that there is a regression with the new version, I was not able to connect to my enterprise VPN using the default settings (I am on bigsur on a 2015 mac).  Got no error, just "not connected"

I rollbacked to the previous version and I am now able to connect again.

FYI, my password a special characters that I cannot remove since it's requested by my company.

Let me know if you need any additional information.

**Comment by axot** [comment]
Hi @Tlzps, I also found if I launched iSstp.app from `Downloads` folder, then the connection fails.
Could you try to put iSstp.app to /Applications and try again?
If it is the case, I think it should be an exists bug, need some further investigation.

**Comment by ghost** [comment]
I launched it from Applications

**Comment by axot** [comment]
Okay, do you use an intel based mac or M1 silicon?

**Comment by ghost** [comment]
Intel based

**Comment by axot** [comment]
Thanks for the feedback, I will test on an intel based machine.

**Comment by axot** [comment]
I created a [rc version](https://github.com/axot/isstp/releases/download/v1.4.1-rc1/iSstp.v1.4.1-rc1.zip) which should fix this. Could you check if it runs on you mac?

**Comment by YannBrrd** [comment]
Hello,

Not connecting neither for me (1.4 .zip is damaged BTW)

**Comment by axot** [comment]
Hi @YannBrrd did you tried the 1.4.1 rc version? https://github.com/axot/isstp/releases/download/v1.4.1-rc1/iSstp.v1.4.1-rc1.zip

**Comment by YannBrrd** [comment]
Just did. Claims "Not connected" each time

**Comment by axot** [comment]
@YannBrrd I tested the rc version in my intel mac, I think it should work if you put isstp.app into `/Applications`. If it works, it's an exists bug, and I will fix it in the next release.

**Comment by YannBrrd** [comment]
Still not. It detects other connnexion to VPN but can't connect itself. ANy log I can look at ?

**Comment by axot** [comment]
@YannBrrd Could you attach the outputs of the following commands?

```
$ ls -al /Applications/iSstp.app/Contents/Resources/
$ otool -L /Applications/iSstp.app/Contents/Resources/sstpc
$ otool -L /Applications/iSstp.app/Contents/MacOS/iSstp
```

**Comment by YannBrrd** [comment]
```
$ ls -al /Applications/iSstp.app/Contents/Resources/
drwxr-xr-x@ 10 yann  staff      320  9 sep 23:43 .
drwxr-xr-x@  8 yann  staff      256  9 sep 23:43 ..
-rw-r--r--@  1 yann  staff    24181  9 sep 23:43 AppIcon.icns
-rw-r--r--@  1 yann  staff    37416  9 sep 23:43 Assets.car
drwxr-xr-x@  3 yann  staff       96  9 sep 23:43 Base.lproj
-rwxr-xr-x@  1 yann  staff   151184  9 sep 23:43 helper
-rw-r--r--@  1 yann  staff      253  9 sep 23:43 install.sh
-rw-r--r--@  1 yann  staff    60627  9 sep 23:43 logo.png
-rwxr-xr-x@  1 yann  staff  5486002  9 sep 23:43 sstpc
-rw-r--r--@  1 yann  staff     1698  9 sep 23:43 statusbar_icon.png

$ otool -L /Applications/iSstp.app/Contents/Resources/sstpc
/Applications/iSstp.app/Contents/Resources/sstpc:
	/usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)

$ otool -L /Applications/iSstp.app/Contents/MacOS/iSstp
/Applications/iSstp.app/Contents/MacOS/iSstp:
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	@rpath/libswiftAppKit.dylib (compatibility version 1.0.0, current version 104.0.0, weak)
	@rpath/libswiftCloudKit.dylib (compatibility version 1.0.0, current version 982.0.0, weak)
	@rpath/libswiftCore.dylib (compatibility version 1.0.0, current version 1205.0.24)
	@rpath/libswiftCoreData.dylib (compatibility version 1.0.0, current version 3.0.0, weak)
	@rpath/libswiftCoreFoundation.dylib (compatibility version 1.0.0, current version 1.6.0, weak)
	@rpath/libswiftCoreGraphics.dylib (compatibility version 1.0.0, current version 2.0.0, weak)
	@rpath/libswiftCoreImage.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
	@rpath/libswiftCoreLocation.dylib (compatibility version 1.0.0, current version 5.0.0, weak)
	@rpath/libswiftDarwin.dylib (compatibility version 1.0.0, current version 0.0.0, weak)
	@rpath/libswiftDispatch.dylib (compatibility version 1.0.0, current version 4.100.1)
	@rpath/libswiftFoundation.dylib (compatibility version 1.0.0, current version 25.102.0)
	@rpath/libswiftIOKit.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
	@rpath/libswiftMetal.dylib (compatibility version 1.0.0, current version 1.3.1, weak)
	@rpath/libswiftObjectiveC.dylib (compatibility version 1.0.0, current version 3.0.0, weak)
	@rpath/libswiftQuartzCore.dylib (compatibility version 1.0.0, current version 1.0.0, weak)
	@rpath/libswiftXPC.dylib (compatibility version 1.0.0, current version 1.1.0, weak)
```

HTH

**Comment by axot** [comment]
@YannBrrd Thanks for the results, it seems install.sh has no execute permission. Let me fix this. In the same time, you could try the following command, then restart iSstp.app. I think it should work.

```
$ chmod +x /Applications/iSstp.app/Contents/Resources/install.sh
```

**Comment by axot** [comment]
I'm trying to remove this install.sh #15.

**Comment by YannBrrd** [comment]
Still not working...

**Comment by axot** [comment]
Sorry for the inconvenience, I understand why you can not connect to the remote sstp server, but I'm keep finding the root cause.
The following command should let it work, but still a mystery.

```
$ cd /Applications/iSstp.app/Contents/Resources
$ ./install.sh
```

**Comment by YannBrrd** [comment]
I think I was not clear abaout the issue. iSstp starts but i can't conect to pmy vpn, whereas I can reach it otherwise

**Comment by axot** [comment]
First, we have an assumption within this thread, v1.3 should work. I found a bug in v1.4.0 which caused intel based mac can't run properly, in this case, I think the new rc release of [v1.4.1](https://github.com/axot/isstp/releases/download/v1.4.1-rc1/iSstp.v1.4.1-rc1.zip) should work.

@YannBrrd Do you have the same situation which v1.3 also works in you environment? If v1.3 not works, it should be another reason.

**Comment by YannBrrd** [comment]
OK, good news! I'm  connecting with 1.3 ...

**Comment by YannBrrd** [comment]
Cleaned and reinstalled 1.4.1rc and launched install.sh and it works 👍
