### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by Denis-Raev** [axot/isstp#16]
Hello! When trying to connect to SSTP, the system displays the following message. How to overcome this problem?

Nov 25 13:56:04 sstpc[18259]: Connect timed out
Nov 25 13:56:04 sstpc[18259]: Could not complete connect to the client
**Error: Could not complete connect to the client, (-1)

**Comment by Denis-Raev** [comment]
<img width="570" alt="Снимок экрана 2021-11-25 в 13 59 26" src="https://user-images.githubusercontent.com/23000390/143429801-26b7d7f0-3db7-4e93-b1a4-eb2946f2b035.png">

**Comment by Denis-Raev** [comment]
Version Mac OS Monterey: 12.0.1 (21A559)
Chip: Apple M1

**Comment by Denis-Raev** [comment]
![image](https://user-images.githubusercontent.com/23000390/143433458-0df10dad-baad-4238-b7ab-0975d9e971a7.png)

When trying to connect via iSttp version 1.4.1 RC-1 constantly writes "Not Connected!".

**Comment by axot** [comment]
Did you try original sstp-client from homebrew?
> brew install sstp-client

**Comment by Denis-Raev** [comment]
> Did you try original sstp-client from homebrew?
> 
> > brew install sstp-client

Yes. No results.

**Comment by Denis-Raev** [comment]
@axot 
![image](https://user-images.githubusercontent.com/23000390/143445884-bb8e98f5-f32d-40e9-85b0-bc47e34b1dec.png)
Here is the output from homebrew's original sttp-client.

**Comment by axot** [comment]
Cloud you try the following options to generate more verbose output?
> --debug --log-level 4 --log-stdout

**Comment by Denis-Raev** [comment]
![image](https://user-images.githubusercontent.com/23000390/143447515-4b6ef469-ea59-473e-bf03-85956f90f18d.png)
I specify the command as in the screenshot above, but now I get a completely different error message.

**Comment by Denis-Raev** [comment]
@axot "sudo /opt/homebrew/Cellar/sstp-client/1.0.16/sbin/sstpc --debug --log-level 4 --log-stdout --cert-warn --user THIS_USER --password THIS_PASSWORD THIS_SERVER"
The command should look like this? I have changed the authorization data.

**Comment by axot** [comment]
The full version command should be like this one.
> sudo /opt/homebrew/Cellar/sstp-client/1.0.16/sbin/sstpc --debug --log-level 4 --log-stdout --cert-warn --user xxx --password xxx THIS_SERVER usepeerdns require-mschap-v2 refuse-eap noauth noipdefault defaultroute noccp

**Comment by Denis-Raev** [comment]
![image](https://user-images.githubusercontent.com/23000390/143454488-6e958762-9bd0-4ad5-a91c-5fb894313778.png)
Entering this command (of course, substituting the authorization data I need), I get the following.

**Comment by Denis-Raev** [comment]
I cannot understand what is the matter.

**Comment by axot** [comment]
Let me check tomorrow.

**Comment by Denis-Raev** [comment]
The command had an extra key --debug

"Nov 25 17:13:48 sstpc[35710]: Resolved vpn.scloud.ru to 141.101.185.157
Nov 25 17:13:48 sstpc[35710]: Connected to vpn.scloud.ru
Nov 25 17:13:48 sstpc[35710]: SSL certificate verification failed: unable to get local issuer certificate (20)
Nov 25 17:13:48 sstpc[35710]: Server certificated failed verification, ignoring
Nov 25 17:13:48 sstpc[35710]: Sending Connect-Request Message
Nov 25 17:13:48 sstpc[35710]: SEND SSTP CRTL PKT(14) 
Nov 25 17:13:48 sstpc[35710]:   TYPE(1): CONNECT REQUEST, ATTR(1):
Nov 25 17:13:48 sstpc[35710]:     ENCAP PROTO(1): 6
Nov 25 17:13:48 sstpc[35710]: RECV SSTP CRTL PKT(48) 
Nov 25 17:13:48 sstpc[35710]:   TYPE(2): CONNECT ACK, ATTR(1):
Nov 25 17:13:48 sstpc[35710]:     CRYPTO BIND REQ(4): 40
Nov 25 17:13:48 sstpc[35710]: Started PPP Link Negotiation
Nov 25 17:13:48 sstpc[35710]: Could not complete write of frame
Nov 25 17:13:48 sstpc[35710]: Could not forward packet to pppd
Nov 25 17:13:50 sstpc[35710]: RECV SSTP CRTL PKT(20) 
Nov 25 17:13:50 sstpc[35710]:   TYPE(6): DISCONNECT, ATTR(1):
Nov 25 17:13:50 sstpc[35710]:     STATUS INFO(2): 12
Nov 25 17:13:50 sstpc[35710]: Sending Disconnect Ack Message
Nov 25 17:13:50 sstpc[35710]: SEND SSTP CRTL PKT(8) 
Nov 25 17:13:50 sstpc[35710]:   TYPE(7): DISCONNECT ACK, ATTR(0):
Nov 25 17:13:50 sstpc[35710]: Connection was aborted, Reason was not known
**Error: Connection was aborted, Reason was not known, (-1)"

**Comment by Denis-Raev** [comment]
Thank you very much for your help! VPN SSTP was raised. Please tell me how to drive all traffic through a VPN gateway and how to route traffic? By default, the connection is established, but no traffic passes through it.

**Comment by Denis-Raev** [comment]
I figured out the routes. But now one question. How can you automate adding routes when starting VPN SSTP via iSttp?

**Comment by axot** [comment]
The `defaultroute` options should add the route table automatically. Did you try this option?

**Comment by Denis-Raev** [comment]
@axot In this case, the user has access only to network resources, there is no Internet access.  It is necessary that routes are automatically added without this parameter and the user has access to both the Internet and the work network.

**Comment by axot** [comment]
Never test, may work for your case, please google `/etc/ppp/ip-up`.

**Comment by Denis-Raev** [comment]
@axot Is it possible to do this in the GUI?

**Comment by axot** [comment]
There is no GUI feature to do this.

**Comment by Denis-Raev** [comment]
Thanks a lot! I configured everything that was required.
