### ISSUE TITLE
Can't get ISSTP to work

### ISSUE THREAD

**Issue by srzelic-zz** [axot/isstp#4]
Hi,
I installed iSSTP and can’t get it to work. Just said (not connected). VPN works from others windows machines. Mschap2 is enabled on server. I have mac OS 10.10.5 yosemite.

Advanced options are default

Do you have any ideas. Thank you

**Comment by RobG000** [comment]
Same for me. Attempting to connect to a VPN on Azure via port 443 like "foo.bar.net:443", no luck. Works fine for Windows users.

My username is like "domain\username". I posted a question on [*SuperUser.com*](https://superuser.com/questions/1234517/connect-to-sstp-vpn-using-mac-os-x) where someone suggested double backslashes but that didn't work either.

One issue is that there is zero feedback other than "Not connected!", which goes away briefly while iSSTP tries to connect, then comes back. I don't know whether it can't find the server, can't login, the certificate is wrong or some other issue.

I have also tried with SSTP from the command line. It seems to attempt to connect but never returns, I guess it doesn't have a timeout. I turned on debug and set logging to 4:

```
Sep 21 16:41:08 sstpc[20411]: Resolved foo.bar.net to <ip address>
Sep 21 16:41:08 sstpc[20411]: TLS hostname extension is enabled
Sep 21 16:41:08 sstpc[20411]: Connected to foo.bar.net
Sep 21 16:41:09 sstpc[20411]: The certificate did not match the host: foo.bar.net:443
Sep 21 16:41:09 sstpc[20411]: Verification of server certificate failed
**Error: Verification of server certificate failed, (-2)

```
foo.bar is not the real name, `<ip address>` is substituted for the real address.

I tried with TLS enabled and disabled, no difference. The server name in the command line is foo.bar.net:443. So it appears to be a certificate issue. What does "(-2)" mean?

**Comment by axot** [comment]
Did you tried this option `require-mschap-v2 noauth defaultroute refuse-eap noccp`

**Comment by srzelic-zz** [comment]
Tried but desn't work. Just to mention that sstp-client (this program is build on) works without a problem.

**Comment by fl0pp** [comment]
I just had a similar problem, and finally found a solution that did the trick. My problem was that I could connect, but I was disconnected 10-30 seconds after. From a Windows 10 machine, I had a stable VPN connection. sstp-client worked perfectly.

The only change is that I have replaced the sstpc file inside the package with the one from the original project.

At first I had to install sstp-client with `brew install sstp-client`.
Then I copied the file with `sudo cp /usr/local/Cellar/sstp-client/1.0.11_1/sbin/sstpc /Applications/iSstp.app/Contents/Resources/sstpc`

I also had to run the following commands:
`cd /Applications/iSstp.app/Contents/Resources`
`sudo rm installed`
`sudo sh ./install.sh`
`otool -L sstpc`

Output from `otool` command:
/Applications/iSstp.app/Contents/Resources/sstpc:
	/usr/local/Cellar/sstp-client/1.0.11_1/lib/libsstp_api-0.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libutil.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/libevent/lib/libevent-2.1.6.dylib (compatibility version 7.0.0, current version 7.2.0)
	/usr/local/opt/openssl/lib/libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)

I was testing on macOS Sierra 10.12.1

**Comment by fl0pp** [comment]
btw, here is the debug log from where I was disconnected:

Oct 12 10:30:26 sstpc[11064]: SSTP DATA PKT(92)
Oct 12 10:30:26 sstpc[11064]: SSTP DATA PKT(60)
Oct 12 10:30:26 sstpc[11064]: SSTP DATA PKT(60)
Oct 12 10:30:26 sstpc[11064]: SSTP DATA PKT(48)
Oct 12 10:30:26 sstpc[11064]: Unrecoverable SSL error
Oct 12 10:30:26 sstpc[11064]: Connection was aborted, Reason was not known
**Error: Connection was aborted, Reason was not known, (-1)

**Comment by SethCalkins** [comment]
`usepeerdns require-mschap-v2 noauth noipdefault defaultroute refuse-eap noccp`

This worked for me.
