### ISSUE TITLE
Cannot connect to Windows 2016 SSTP server with EAP from High-Sierra

### ISSUE THREAD

**Issue by renecuchet** [axot/isstp#5]
I am trying to connect to a Windows 2016 with need EAP.
hier is the log and my command for trying to command.. We can see that I receive a EAP message from the server but I can't answer..
MacBook-Pro-van-Rene:~ renecuchet$ sudo /usr/local/sbin/sstpc --log-level 5 --log-stderr --cert-warn --user rene.cuchet@xxxxxx.xx --password xxxxxxxxxx vpn.xxxxx.io usepeerdns require-mschap-v2 noauth noipdefault  noccp
Jun 12 18:30:27 sstpc[50356]: Resolved vpn.xxxxxx.io to xxx.xxx..xxx.xxx
Jun 12 18:30:27 sstpc[50356]: Connected to vpn.wem.io
Jun 12 18:30:27 sstpc[50356]: Sending Connect-Request Message
Jun 12 18:30:27 sstpc[50356]: SEND SSTP CRTL PKT(14) 
Jun 12 18:30:27 sstpc[50356]:   TYPE(1): CONNECT REQUEST, ATTR(1):
Jun 12 18:30:27 sstpc[50356]:     ENCAP PROTO(1): 6
Jun 12 18:30:27 sstpc[50356]: RECV SSTP CRTL PKT(48) 
Jun 12 18:30:27 sstpc[50356]:   TYPE(2): CONNECT ACK, ATTR(1):
Jun 12 18:30:27 sstpc[50356]:     CRYPTO BIND REQ(4): 40
Jun 12 18:30:27 sstpc[50356]: Started PPP Link Negotiation
Jun 12 18:30:27 sstpc[50356]: SEND SSTP DATA PKT(28) 
Jun 12 18:30:27 sstpc[50356]:   PPP LCP ID: 1  CONFREQ ASYNCMAP: 00 00 00 00 MAGIC: 0x4C5D9750
Jun 12 18:30:27 sstpc[50356]: RECV SSTP DATA PKT(60) 
Jun 12 18:30:27 sstpc[50356]:   PPP LCP ID: 0  CONFREQ MRU: 4091 AUTH: EAP MAGIC: 0x51A2411C CALLBACK: 06 MRRU: 1614 EPDISC: 01 EF 8B 14 35 C0 16 4A 55 A0 7E F5 4F 35 30 3B EE 00 00 00 00
Jun 12 18:30:27 sstpc[50356]: RECV SSTP DATA PKT(28) 
Jun 12 18:30:27 sstpc[50356]:   PPP LCP ID: 1  CONFACK ASYNCMAP: 00 00 00 00 MAGIC: 0x4C5D9750
Jun 12 18:30:27 sstpc[50356]: SEND SSTP DATA PKT(19) 
Jun 12 18:30:27 sstpc[50356]:   PPP LCP ID: 0  CONFREJ CALLBACK: 06 MRRU: 1614
Jun 12 18:30:27 sstpc[50356]: RECV SSTP DATA PKT(53) 
Jun 12 18:30:27 sstpc[50356]:   PPP LCP ID: 1  CONFREQ MRU: 4091 AUTH: EAP MAGIC: 0x51A2411C EPDISC: 01 EF 8B 14 35 C0 16 4A 55 A0 7E F5 4F 35 30 3B EE 00 00 00 00
Jun 12 18:30:27 sstpc[50356]: SEND SSTP DATA PKT(53) 
Jun 12 18:30:27 sstpc[50356]:   PPP LCP ID: 1  CONFACK MRU: 4091 AUTH: EAP MAGIC: 0x51A2411C EPDISC: 01 EF 8B 14 35 C0 16 4A 55 A0 7E F5 4F 35 30 3B EE 00 00 00 00
Jun 12 18:30:27 sstpc[50356]: RECV SSTP DATA PKT(11) 
Jun 12 18:30:27 sstpc[50356]:   PPP EAP ID: 0  CONFREQ 0x01 
Jun 12 18:30:27 sstpc[50356]: SEND SSTP DATA PKT(30) 
Jun 12 18:30:27 sstpc[50356]:   PPP EAP ID: 0  CONFACK 0x01 0x72 0x65 0x6E 0x65 0x2E 0x63 0x75 0x63 0x68 0x65 0x74 0x40 0x77 0x65 0x6D 0x2E 0x64 0x65 0x76 
Jun 12 18:30:27 sstpc[50356]: RECV SSTP DATA PKT(35) 
Jun 12 18:30:27 sstpc[50356]:   PPP EAP ID: 1  CONFREQ 0x1A 0x01 0x01 0x00 0x18 0x10 0xD8 0xC3 0x0E 0x6F 0xCA 0x15 0x5C 0xD3 0xC3 0x0B 0xA8 0x79 0x47 0x59 0xA9 0xF2 0x56 0x50 0x4E 
Jun 12 18:30:39 sstpc[50356]: RECV SSTP DATA PKT(35) 
Jun 12 18:30:39 sstpc[50356]:   PPP EAP ID: 1  CONFREQ 0x1A 0x01 0x01 0x00 0x18 0x10 0xD8 0xC3 0x0E 0x6F 0xCA 0x15 0x5C 0xD3 0xC3 0x0B 0xA8 0x79 0x47 0x59 0xA9 0xF2 0x56 0x50 0x4E 
Jun 12 18:30:51 sstpc[50356]: RECV SSTP DATA PKT(35) 
Jun 12 18:30:51 sstpc[50356]:   PPP EAP ID: 1  CONFREQ 0x1A 0x01 0x01 0x00 0x18 0x10 0xD8 0xC3 0x0E 0x6F 0xCA 0x15 0x5C 0xD3 0xC3 0x0B 0xA8 0x79 0x47 0x59 0xA9 0xF2 0x56 0x50 0x4E 
Jun 12 18:31:03 sstpc[50356]: RECV SSTP DATA PKT(35) 
Jun 12 18:31:03 sstpc[50356]:   PPP EAP ID: 1  CONFREQ 0x1A 0x01 0x01 0x00 0x18 0x10 0xD8 0xC3 0x0E 0x6F 0xCA 0x15 0x5C 0xD3 0xC3 0x0B 0xA8 0x79 0x47 0x59 0xA9 0xF2 0x56 0x50 0x4E 
Jun 12 18:31:15 sstpc[50356]: RECV SSTP DATA PKT(35) 
Jun 12 18:31:15 sstpc[50356]:   PPP EAP ID: 1  CONFREQ 0x1A 0x01 0x01 0x00 0x18 0x10 0xD8 0xC3 0x0E 0x6F 0xCA 0x15 0x5C 0xD3 0xC3 0x0B 0xA8 0x79 0x47 0x59 0xA9 0xF2 0x56 0x50 0x4E 
Jun 12 18:31:27 sstpc[50356]: RECV SSTP CRTL PKT(20) 
Jun 12 18:31:27 sstpc[50356]:   TYPE(5): ABORT, ATTR(1):
Jun 12 18:31:27 sstpc[50356]:     STATUS INFO(2): 12
Jun 12 18:31:27 sstpc[50356]: Connection was aborted, Reason was not known
**Error: Connection was aborted, Reason was not known, (-1)

**Comment by CarelvanHeerden** [comment]
Has any progress been made on this bug? I have the exact same issue

**Comment by renecuchet** [comment]
Hi Carel,
Yes I found a solution for that issue: 
SSTP server had as authentication method only (Microsoft: Protected EAP (PEAP).
I added the authentication method:  Microsoft Encrypted Authentication version 2 (MS-CHAP v2)
and it worked.
But I also saw that it can be an issue with the password used by the user connecting. Few special characters are not accepted.
