### ISSUE TITLE
can't connect with the code in git

### ISSUE THREAD

**Issue by DeforeChen** [axot/isstp#7]
I download iSSTP.app from your blog which works. But I build and run the code from your git, there is always print "dyld: Library not loaded: /usr/local/lib/libevent-2.0.5.dylib, Reason: image not found" and can't connect to VPN.

The promble seems that they are different version. one is 20161004 and the release is 20161009.

Would you please help to solve it? Or I guess the latest code has not been committed yet.

**Comment by axot** [comment]
Yes, to run this with Xcode, you need install dependencies.

```
brew install libevent openssl@1.1
```

or you can also install sstpc from homebrew

```
brew install sstp-client
```

And then, use the path as an external sstpc setup like the following example.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/611054/130871318-09c30832-7692-4a6f-9653-f8d2af8a0535.png">
