### ISSUE TITLE
ppp0 does not exist

### ISSUE THREAD

**Issue by renatosc** [axot/isstp#8]
I am not being able to connect to my vpnazure.net VPN.  Since the client doesn't provide feedback on what failed (just doesn't connect), I ran the project from source and I see this on my console:

> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> **Error: HTTP handshake with server failed, (-1)
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist
> ifconfig: interface ppp0 does not exist

Is the interface ppp0 required to run this software?

**Comment by axot** [comment]
It means the VPN connection failed, Please check the latest version.
