### ISSUE TITLE
PAP connection

### ISSUE THREAD

**Issue by albertovm** [axot/isstp#9]
Hi, I am not able to connect using ISSTP, but it works manually (however... no DNS).

sudo /usr/local/sbin/sstpc --cert-warn --user <user> --password <pass> <server> require-pap noauth usepeerdns noipdefault defaultroute refuse-eap noccp --log-level 3 --log-stdout

After connect manually, it appears as Connected in ISSTP interface too.
Any idea about how to configure it into ISSTP?

Is there any way to force DNS server too? Because I have no DNS server enable when connected to VPN server.

Thanks a lot.

**Comment by axot** [comment]
> Any idea about how to configure it into ISSTP?

There is an Edit button, you can put all these options there.
<img width="771" alt="image" src="https://user-images.githubusercontent.com/611054/130871493-9521fbee-ada4-40af-8ee9-bbd7edd267b4.png">

> Is there any way to force DNS server too?

Maybe you can try to create a `/etc/ppp/ip-up` script to add these DNS servers in `/etc/ppp/resolv.conf`
